POST http://localhost:5000/comments/here-is-a-second-post
content-type: application/json

{
    "text": "the 6th comment",
    "userId": "5fe23c6abdafa758b46d96c0"

}

###

GET http://localhost:5000/comments/here-is-a-sample-post
content-type: application/json

###