POST http://localhost:5000/comments/nodejs-performance-tips-210279bc-590c-4993-843b-cd6a0e0308be
content-type: application/json

{
    "text": "the 7th comment",
    "sub": "116539756123146752273"
}

###

GET http://localhost:5000/comments/nodejs-performance-tips-210279bc-590c-4993-843b-cd6a0e0308be
content-type: application/json

###