DELETE http://localhost:5000/posts/asdgas
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmQ2OWRiYjAyYTYzYjYyNzU4N2RhOTgiLCJ1c2VyTmFtZSI6IkxsYW5kZGV3aUxvdmVzWW91IiwicGFzc3dvcmQiOiIkMmIkMTAkaC9xVGl6dWMvZTlzc3hzVENpWmt2dWI2bTZUL25wanJJRlhiV25pdEg1bzFtRTVwUHdWZkciLCJwZXJtaXNzaW9ucyI6ImFkbWluIiwiY3JlYXRlZEF0IjoiMjAyMC0xMi0xM1QyMzowMzoyMy43MjBaIiwidXBkYXRlZEF0IjoiMjAyMC0xMi0xM1QyMzowMzoyMy43MjBaIiwiX192IjowLCJpYXQiOjE2MDgwNzQ5OTF9.0-64ircWRQZgW_OvHEikWP1KMDH9ld_AWBs_6RXfnHc

###

GET  http://localhost:5000/posts

###

POST  http://localhost:5000/posts
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmQ2OWRiYjAyYTYzYjYyNzU4N2RhOTgiLCJ1c2VyTmFtZSI6IkxsYW5kZGV3aUxvdmVzWW91IiwicGFzc3dvcmQiOiIkMmIkMTAkaC9xVGl6dWMvZTlzc3hzVENpWmt2dWI2bTZUL25wanJJRlhiV25pdEg1bzFtRTVwUHdWZkciLCJwZXJtaXNzaW9ucyI6ImFkbWluIiwiY3JlYXRlZEF0IjoiMjAyMC0xMi0xM1QyMzowMzoyMy43MjBaIiwidXBkYXRlZEF0IjoiMjAyMC0xMi0xM1QyMzowMzoyMy43MjBaIiwiX192IjowLCJpYXQiOjE2MDgwNzQ5OTF9.0-64ircWRQZgW_OvHEikWP1KMDH9ld_AWBs_6RXfnHc

{
     "id": "string",
    "title": "string",
     "subtitle": "string",
     "body": "string",
    "wordCount": "123",
     "author": "string",
     "imageUrl": "string"
}