
GET http://localhost:5000/users/
authorization: Bearer

###

//create user
POST http://localhost:5000/users
content-type: application/json
authorization: Bearer

{
  "iss": "https://accounts.google.com",
  "azp": "795928167105-a84o5k11ga71smag05h8c96jc8gkc575.apps.googleusercontent.com",
  "aud": "795928167105-a84o5k11ga71smag05h8c96jc8gkc575.apps.googleusercontent.com",
  "sub": "107672084474241639249",
  "email": "iandelduca@gmail.com",
  "email_verified": true,
  "at_hash": "Q3Hn2WzaYdE8O2p0EVP4hA",
  "name": "WORK EMAIL",
  "picture": "https://lh3.googleusercontent.com/a/ACg8ocIfkqj5M5rgW3mzosRzlyOXDpcc_z9FcJ_dwUOwW_8_EzCNUw=s96-c",
  "given_name": "WORK",
  "family_name": "EMAIL",
  "iat": 1778094803,
  "exp": 1778098403
}

###

DELETE  http://localhost:5000/users/sampleuser
content-type: application/json
authorization: Bearer


{
    "userName": "LlanddewiLovesYou",
    "password": "Brefi1979!",
    "permissions": "admin"
}

###

//login
POST http://localhost:5000/users/login
content-type: application/json

{
    "userName": "LlanddewiLovesYou",
    "password": "Brefi1979!"
}

###

// validate token
POST http://localhost:5000/users/validate
Content-Type: application/json

{
    "accessToken": ""
}